# Generated by Django 5.2.1 on 2025-09-14 22:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                help_text="شماره تماس برای ورود به سیستم استفاده می\u200cشود.",
                max_length=11,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="شماره تماس باید ۱۱ رقم باشد.", regex="^\\d{11}$"
                    )
                ],
                verbose_name="phone number",
            ),
        ),
    ]
