# Generated by Django 5.2.1 on 2025-09-15 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                help_text="عکس پروفایل کاربر",
                null=True,
                upload_to="profiles/images/",
                verbose_name="تصویر پروفایل",
            ),
        ),
    ]
