# Generated by Django 5.2.6 on 2025-09-17 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_profile_profile_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="current_session_key",
        ),
        migrations.AddField(
            model_name="user",
            name="active_jti",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True, unique=True
            ),
        ),
    ]
