# Generated by Django 5.2.1 on 2025-09-18 08:39

import apps.accounts.models.profile
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_user_current_session_key_user_active_jti"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="auth_image",
        ),
        migrations.CreateModel(
            name="AuthenticationDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.accounts.models.profile.get_auth_document_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png", "pdf"]
                            )
                        ],
                        verbose_name="فایل مدرک",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="زمان بارگذاری"
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="accounts.profile",
                        verbose_name="پروفایل",
                    ),
                ),
            ],
            options={
                "verbose_name": "مدرک هویتی",
                "verbose_name_plural": "مدارک هویتی",
            },
        ),
    ]
