# Generated by Django 5.2.1 on 2025-09-18 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_remove_profile_auth_image_authenticationdocument"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(default=1, max_length=254, verbose_name="ایمیل"),
            preserve_default=False,
        ),
    ]
