# Generated by Django 5.2.1 on 2025-09-25 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_user_email"),
        ("prescriptions", "0004_prescription_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="saved_prescriptions",
            field=models.ManyToManyField(
                blank=True,
                related_name="savers",
                to="prescriptions.prescription",
                verbose_name="نسخه\u200cهای ذخیره\u200cشده",
            ),
        ),
    ]
