# Generated by Django 5.2.1 on 2025-10-17 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_user_saved_prescriptions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="medical_code",
            field=models.CharField(
                blank=True,
                default="DR-CODE",
                max_length=50,
                null=True,
                verbose_name="کد نظام پزشکی / دانشجویی",
            ),
        ),
    ]
