# Generated by Django 5.2.7 on 2025-11-22 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_alter_profile_medical_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="medical_code",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="کد نظام پزشکی / دانشجویی",
            ),
        ),
    ]
