# Generated by Django 5.2.1 on 2025-11-24 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_alter_profile_medical_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_phone_verified",
            field=models.BooleanField(default=False, verbose_name="تایید شماره تلفن"),
        ),
    ]
