# Generated by Django 5.2.1 on 2025-09-16 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("prescriptions", "0004_alter_prescription_slug"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField(verbose_name="متن سوال")),
                (
                    "answer_text",
                    models.TextField(
                        blank=True, null=True, verbose_name="متن پاسخ ادمین"
                    ),
                ),
                (
                    "is_answered",
                    models.BooleanField(default=False, verbose_name="پاسخ داده شده؟"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاریخ ثبت سوال"
                    ),
                ),
                (
                    "answered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاریخ ثبت پاسخ"
                    ),
                ),
                (
                    "answered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="answered_questions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="پاسخ\u200cدهنده",
                    ),
                ),
                (
                    "prescription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="prescriptions.prescription",
                        verbose_name="نسخه مربوطه",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر سوال\u200cکننده",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_answered"],
                        name="questions_q_user_id_3b1108_idx",
                    ),
                    models.Index(
                        fields=["prescription", "is_answered"],
                        name="questions_q_prescri_0ebec3_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="questions_q_created_d1d888_idx"
                    ),
                ],
            },
        ),
    ]
