# Generated by Django 5.2.1 on 2025-09-14 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="نام دسته\u200cبندی"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True, unique=True, verbose_name="اسلاگ (آدرس)"
                    ),
                ),
                (
                    "color_code",
                    models.CharField(
                        help_text="کد هگزادسیمال رنگ، مانند #FF5733",
                        max_length=7,
                        verbose_name="کد رنگ",
                    ),
                ),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان نسخه")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True, unique=True, verbose_name="اسلاگ (آدرس)"
                    ),
                ),
                (
                    "is_premium",
                    models.BooleanField(default=True, verbose_name="نسخه ویژه است؟"),
                ),
                (
                    "detailed_description",
                    models.TextField(
                        blank=True, null=True, verbose_name="توضیحات تکمیلی (صفحه مجزا)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prescriptions",
                        to="prescriptions.category",
                        verbose_name="دسته\u200cبندی",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PrescriptionDrug",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="نام دارو")),
                (
                    "code",
                    models.CharField(blank=True, max_length=50, verbose_name="کد دارو"),
                ),
                (
                    "dosage",
                    models.CharField(max_length=200, verbose_name="دوز و نحوه مصرف"),
                ),
                ("amount", models.IntegerField(default=0, verbose_name="مقدار دارو")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="توضیحات کوتاه دارو"),
                ),
                (
                    "group",
                    models.CharField(
                        blank=True,
                        help_text="برای گروه\u200cبندی بصری داروها با رنگ یکسان (مثلا: antibiotics-group)",
                        max_length=50,
                        verbose_name="گروه دارویی",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتیب نمایش"),
                ),
                (
                    "prescription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drugs",
                        to="prescriptions.prescription",
                        verbose_name="نسخه مرجع",
                    ),
                ),
            ],
            options={
                "verbose_name": "داروی نسخه",
                "verbose_name_plural": "داروهای نسخه\u200cها",
                "ordering": ["order"],
            },
        ),
    ]
