# Generated by Django 5.2.1 on 2025-09-16 11:01

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PrescriptionCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="نام دسته\u200cبندی"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True, unique=True, verbose_name="اسلاگ (آدرس)"
                    ),
                ),
                (
                    "color_code",
                    models.CharField(
                        help_text="کد هگزادسیمال رنگ، مانند #FF5733",
                        max_length=7,
                        verbose_name="کد رنگ",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ساخت"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="زمان بروزرسانی"),
                ),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان نسخه")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True, unique=True, verbose_name="اسلاگ (آدرس)"
                    ),
                ),
                (
                    "access_level",
                    models.CharField(
                        choices=[("FREE", "رایگان"), ("PREMIUM", "ویژه")],
                        default="FREE",
                        max_length=10,
                        verbose_name="سطح دسترسی",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="نسخه\u200cهای غیرفعال نمایش داده نمی\u200cشوند",
                        verbose_name="فعال",
                    ),
                ),
                (
                    "detailed_description",
                    django_ckeditor_5.fields.CKEditor5Field(verbose_name="Text"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prescriptions",
                        to="prescriptions.prescriptioncategory",
                        verbose_name="دسته\u200cبندی",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PrescriptionDrug",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="نام دارو")),
                (
                    "code",
                    models.CharField(blank=True, max_length=50, verbose_name="کد دارو"),
                ),
                (
                    "dosage",
                    models.CharField(max_length=200, verbose_name="دوز و نحوه مصرف"),
                ),
                ("amount", models.IntegerField(default=0, verbose_name="مقدار دارو")),
                (
                    "instructions",
                    models.TextField(blank=True, verbose_name="توضیحات کوتاه دارو"),
                ),
                (
                    "is_combination",
                    models.BooleanField(
                        default=False,
                        help_text="آیا این دارو جزء گروه داروهای ترکیبی است؟",
                        verbose_name="دارویی ترکیبی",
                    ),
                ),
                (
                    "combination_group",
                    models.CharField(
                        blank=True,
                        help_text="برای گروه\u200cبندی بصری داروها با رنگ یکسان (مثلا: antibiotics-group)",
                        max_length=50,
                        verbose_name="گروه دارویی",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتیب نمایش"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ساخت"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="زمان بروزرسانی"),
                ),
                (
                    "prescription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drugs",
                        to="prescriptions.prescription",
                        verbose_name="نسخه مرجع",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="PrescriptionImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="prescriptions/images/", verbose_name="فایل تصویر"
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="کپشن تصویر"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ساخت"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="زمان بروزرسانی"),
                ),
                (
                    "prescription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="prescriptions.prescription",
                        verbose_name="نسخه مرجع",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PrescriptionVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video_url", models.URLField(verbose_name="لینک ویدیو (آپارات)")),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="عنوان ویدیو"
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ساخت"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="زمان بروزرسانی"),
                ),
                (
                    "prescription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="prescriptions.prescription",
                        verbose_name="نسخه مرجع",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PrescriptionAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="نام جایگزین")),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="آیا این نام اصلی نسخه است؟",
                        verbose_name="نام اصلی",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "prescription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="prescriptions.prescription",
                        verbose_name="نسخه",
                    ),
                ),
            ],
            options={
                "verbose_name": "نام جایگزین",
                "verbose_name_plural": "نام\u200cهای جایگزین",
                "unique_together": {("prescription", "name")},
            },
        ),
    ]
