# Generated by Django 5.2.1 on 2025-09-25 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("prescriptions", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prescriptiondrug",
            name="combination_group",
        ),
    ]
