# Generated by Django 5.2.1 on 2025-09-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prescriptions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prescriptioncategory",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, blank=True, unique=True, verbose_name="اسلاگ (آدرس)"
            ),
        ),
    ]
