# Generated by Django 5.2.1 on 2025-09-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prescriptions", "0002_alter_prescriptioncategory_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prescriptioncategory",
            name="color_code",
            field=models.CharField(
                help_text="کد هگزادسیمال رنگ، مانند #FF5733",
                max_length=20,
                verbose_name="کد رنگ",
            ),
        ),
    ]
