# Generated by Django 5.2.1 on 2025-09-25 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("prescriptions", "0002_remove_prescriptiondrug_combination_group"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="prescriptiondrug",
            unique_together=set(),
        ),
    ]
