# Generated by Django 5.2.1 on 2025-09-16 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prescriptions", "0003_alter_prescriptioncategory_color_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prescription",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, blank=True, unique=True, verbose_name="اسلاگ (آدرس)"
            ),
        ),
    ]
