# Generated by Django 5.2.1 on 2025-10-05 15:46

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("prescriptions", "0004_prescription_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescription",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="prescription",
            name="detailed_description",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="Text"
            ),
        ),
    ]
