# Generated by Django 5.2.1 on 2025-10-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prescriptions", "0005_prescription_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drug",
            name="code",
            field=models.CharField(
                blank=True, max_length=50, unique=True, verbose_name="کد دارو"
            ),
        ),
        migrations.AlterField(
            model_name="drug",
            name="title",
            field=models.CharField(
                max_length=150, unique=True, verbose_name="نام دارو"
            ),
        ),
    ]
