# Generated by Django 5.2.1 on 2025-10-05 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prescriptions", "0006_alter_drug_code_alter_drug_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="DrugGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="نام گروه"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="توضیحات گروه"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ساخت"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="زمان بروزرسانی"),
                ),
            ],
            options={
                "verbose_name": "گروه دارویی",
                "verbose_name_plural": "گروه\u200cهای دارویی",
            },
        ),
        migrations.AddField(
            model_name="drug",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="drugs",
                to="prescriptions.druggroup",
                verbose_name="گروه\u200cهای دارویی",
            ),
        ),
        migrations.AddField(
            model_name="prescriptiondrug",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="prescriptions.druggroup",
                verbose_name="گروه دارویی",
            ),
        ),
    ]
