# Generated by Django 5.2.1 on 2025-10-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prescriptions", "0007_druggroup_drug_groups_prescriptiondrug_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="drug",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="prescriptiondrug",
            name="group",
        ),
        migrations.AddField(
            model_name="prescriptiondrug",
            name="group_number",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="برای گروه\u200cبندی داروها در یک نسخه استفاده می\u200cشود",
                null=True,
                verbose_name="شماره گروه دارویی",
            ),
        ),
        migrations.DeleteModel(
            name="DrugGroup",
        ),
    ]
