# Generated by Django 5.2.1 on 2025-10-06 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "prescriptions",
            "0008_remove_drug_groups_remove_prescriptiondrug_group_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="prescriptiondrug",
            name="is_substitute",
            field=models.BooleanField(
                default=False,
                help_text="این گزینه را برای داروهایی که می\u200cتوانند با یکدیگر جایگزین شوند، فعال کنید",
                verbose_name="داروی جایگزین",
            ),
        ),
    ]
