# Generated by Django 5.2.1 on 2025-10-09 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prescriptions", "0009_prescriptiondrug_is_substitute"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drug",
            name="code",
            field=models.CharField(blank=True, max_length=50, verbose_name="کد دارو"),
        ),
    ]
