# Generated by Django 5.2.6 on 2025-10-17 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0010_alter_drug_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionimage',
            name='is_compressed',
            field=models.BooleanField(default=False, verbose_name='فشرده شده؟'),
        ),
    ]
