# Generated by Django 5.2.6 on 2025-10-30 06:28

import apps.prescriptions.models.prescription_image
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0011_prescriptionimage_is_compressed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptionimage',
            name='image',
            field=models.ImageField(upload_to=apps.prescriptions.models.prescription_image.get_prescription_image_path, verbose_name='فایل تصویر'),
        ),
    ]
