# Generated by Django 6.0.6 on 2026-06-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0012_alter_prescriptionimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='is_for_order',
            field=models.BooleanField(default=False, verbose_name='آیا برای اوردر است؟'),
        ),
    ]
