# Generated by Django 5.2.1 on 2025-09-15 11:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=150, verbose_name="نام و نام خانوادگی"),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254,
                        validators=[django.core.validators.EmailValidator()],
                        verbose_name="ایمیل",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="شماره تماس"
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            ("support", "پشتیبانی پزشکی"),
                            ("suggestion", "پیشنهاد"),
                            ("complaint", "شکایت"),
                            ("question", "سوال عمومی"),
                            ("cooperation", "همکاری"),
                            ("other", "سایر موارد"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="موضوع",
                    ),
                ),
                (
                    "custom_subject",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="موضوع سفارشی",
                    ),
                ),
                ("message", models.TextField(verbose_name="متن پیام")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار بررسی"),
                            ("in_progress", "در حال بررسی"),
                            ("answered", "پاسخ داده شده"),
                            ("closed", "بسته شده"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "admin_response",
                    models.TextField(blank=True, null=True, verbose_name="پاسخ ادمین"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ارسال"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "responded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاریخ پاسخ"
                    ),
                ),
                (
                    "responded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contact_responses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="پاسخ\u200cدهنده",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="کاربر ثبت\u200cنام شده (در صورت وجود)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "پیام تماس",
                "verbose_name_plural": "پیام\u200cهای تماس",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="home_contac_status_9ff996_idx"
                    ),
                    models.Index(
                        fields=["subject"], name="home_contac_subject_7d3d2f_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="home_contac_created_6e9921_idx"
                    ),
                ],
            },
        ),
    ]
