# Generated by Django 5.2.1 on 2025-09-15 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tutorial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان ویدیو")),
                (
                    "description",
                    models.TextField(
                        help_text="توضیح مختصری از محتوای ویدیو", verbose_name="توضیحات"
                    ),
                ),
                (
                    "aparat_url",
                    models.URLField(
                        help_text="لینک کامل ویدیو در آپارات",
                        verbose_name="لینک آپارات",
                    ),
                ),
                (
                    "aparat_id",
                    models.CharField(
                        help_text="شناسه منحصر به فرد ویدیو در آپارات (خودکار استخراج می\u200cشود)",
                        max_length=50,
                        unique=True,
                        verbose_name="شناسه آپارات",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("getting_started", "شروع کار با سامانه"),
                            ("prescription_usage", "نحوه استفاده از نسخه\u200cها"),
                            ("search_filter", "جستجو و فیلتر کردن"),
                            ("account_management", "مدیریت حساب کاربری"),
                            ("qa_system", "سیستم پرسش و پاسخ"),
                            ("subscription", "اشتراک و خرید"),
                            ("advanced_features", "ویژگی\u200cهای پیشرفته"),
                            ("troubleshooting", "عیب\u200cیابی و مشکلات رایج"),
                            ("general", "عمومی"),
                        ],
                        default="general",
                        max_length=30,
                        verbose_name="دسته\u200cبندی",
                    ),
                ),
                (
                    "duration",
                    models.CharField(
                        blank=True,
                        help_text="مدت زمان ویدیو (مثال: 05:30)",
                        max_length=20,
                        null=True,
                        verbose_name="مدت زمان",
                    ),
                ),
                (
                    "thumbnail_url",
                    models.URLField(
                        blank=True,
                        help_text="لینک تصویر کوچک ویدیو (خودکار از آپارات گرفته می\u200cشود)",
                        null=True,
                        verbose_name="تصویر کوچک",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="عدد کوچکتر = اولویت بالاتر",
                        verbose_name="ترتیب نمایش",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "پیش\u200cنویس"),
                            ("published", "منتشر شده"),
                            ("archived", "بایگانی شده"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="نمایش در بخش ویدیوهای ویژه",
                        verbose_name="ویدیوی ویژه",
                    ),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(default=0, verbose_name="تعداد بازدید"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ایجاد شده توسط",
                    ),
                ),
            ],
            options={
                "verbose_name": "ویدیوی آموزشی",
                "verbose_name_plural": "ویدیوهای آموزشی",
                "ordering": ["order", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["category"], name="home_tutori_categor_ed2c2f_idx"
                    ),
                    models.Index(
                        fields=["status"], name="home_tutori_status_4b01a6_idx"
                    ),
                    models.Index(
                        fields=["is_featured"], name="home_tutori_is_feat_8399c2_idx"
                    ),
                    models.Index(fields=["order"], name="home_tutori_order_ba3107_idx"),
                ],
            },
        ),
    ]
