# Generated by Django 5.2.1 on 2025-09-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_tutorial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tutorial",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "ویدیوی آموزشی",
                "verbose_name_plural": "ویدیوهای آموزشی",
            },
        ),
        migrations.RemoveIndex(
            model_name="tutorial",
            name="home_tutori_categor_ed2c2f_idx",
        ),
        migrations.RemoveIndex(
            model_name="tutorial",
            name="home_tutori_status_4b01a6_idx",
        ),
        migrations.RemoveIndex(
            model_name="tutorial",
            name="home_tutori_is_feat_8399c2_idx",
        ),
        migrations.RemoveIndex(
            model_name="tutorial",
            name="home_tutori_order_ba3107_idx",
        ),
        migrations.RemoveField(
            model_name="tutorial",
            name="aparat_id",
        ),
        migrations.RemoveField(
            model_name="tutorial",
            name="category",
        ),
        migrations.RemoveField(
            model_name="tutorial",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="tutorial",
            name="duration",
        ),
        migrations.RemoveField(
            model_name="tutorial",
            name="is_featured",
        ),
        migrations.RemoveField(
            model_name="tutorial",
            name="order",
        ),
        migrations.RemoveField(
            model_name="tutorial",
            name="status",
        ),
        migrations.RemoveField(
            model_name="tutorial",
            name="thumbnail_url",
        ),
        migrations.RemoveField(
            model_name="tutorial",
            name="view_count",
        ),
        migrations.AlterField(
            model_name="tutorial",
            name="aparat_url",
            field=models.URLField(
                help_text="لینک کامل ویدیو در آپارات", verbose_name="آدرس آپارات"
            ),
        ),
        migrations.AlterField(
            model_name="tutorial",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="زمان ساخت"),
        ),
        migrations.AlterField(
            model_name="tutorial",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="توضیح اختیاری از محتوای ویدیو",
                null=True,
                verbose_name="توضیحات",
            ),
        ),
        migrations.AlterField(
            model_name="tutorial",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="زمان بروزرسانی"),
        ),
    ]
