# Generated by Django 5.2.1 on 2025-09-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_alter_tutorial_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tutorial",
            name="title",
            field=models.CharField(max_length=255, verbose_name="عنوان ویدیو"),
        ),
    ]
