# Generated by Django 5.2.1 on 2025-09-15 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_alter_tutorial_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tutorial",
            name="aparat_url",
            field=models.URLField(
                help_text="لینک کامل ویدیو در آپارات",
                max_length=255,
                verbose_name="آدرس آپارات",
            ),
        ),
    ]
