# Generated by Django 5.2.6 on 2025-10-13 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_alter_tutorial_aparat_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tutorial",
            name="aparat_url",
            field=models.URLField(
                help_text="لینک کامل ویدیو در آپارات",
                max_length=600,
                verbose_name="آدرس آپارات",
            ),
        ),
    ]
