# Generated by Django 5.2.6 on 2025-10-13 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_alter_tutorial_aparat_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tutorial",
            name="description",
        ),
    ]
