# Generated by Django 5.2.6 on 2025-10-13 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_remove_tutorial_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tutorial",
            name="aparat_url",
            field=models.CharField(
                help_text="لینک کامل ویدیو در آپارات",
                max_length=700,
                verbose_name="آدرس آپارات",
            ),
        ),
    ]
