# Generated by Django 5.2.6 on 2025-10-21 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_remove_tutorial_description_and_more"),
        ("home", "0009_alter_tutorial_aparat_url"),
    ]

    operations = []
