# Generated by Django 5.2.10 on 2026-05-27 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_tutorial_description_alter_contact_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='description',
        ),
    ]
