# Generated by Django 5.2.1 on 2025-09-16 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="نام نوع اشتراک"
                    ),
                ),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="فعال است؟"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="نام بسته")),
                (
                    "duration_days",
                    models.PositiveIntegerField(verbose_name="مدت زمان (به روز)"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=0, max_digits=12, verbose_name="قیمت (ریال)"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="بسته فعال است؟"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plans",
                        to="subscriptions.membership",
                        verbose_name="برای کدام نوع اشتراک؟",
                    ),
                ),
            ],
            options={
                "ordering": ["duration_days"],
                "unique_together": {("membership", "duration_days")},
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_amount",
                    models.DecimalField(
                        decimal_places=0,
                        help_text="مبلغ واقعی که کاربر پرداخت کرده (بعد از تخفیف)",
                        max_digits=12,
                        verbose_name="مبلغ پرداختی (تومان)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "فعال"),
                            ("EXPIRED", "منقضی\u200cشده"),
                            ("CANCELED", "لغو شده"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                        verbose_name="وضعیت اشتراک",
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ شروع"),
                ),
                ("end_date", models.DateTimeField(verbose_name="تاریخ انقضا")),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="subscriptions.plan",
                        verbose_name="پلن",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "اشتراک کاربر",
                "verbose_name_plural": "اشتراک\u200cهای کاربران",
                "ordering": ["-end_date"],
                "indexes": [
                    models.Index(
                        fields=["user", "-end_date"],
                        name="subscriptio_user_id_2dee56_idx",
                    ),
                    models.Index(
                        fields=["end_date", "status"],
                        name="subscriptio_end_dat_1aba83_idx",
                    ),
                ],
            },
        ),
    ]
