# Generated by Django 5.2.6 on 2025-09-17 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "در انتظار پرداخت"),
                    ("ACTIVE", "فعال"),
                    ("EXPIRED", "منقضی\u200cشده"),
                    ("CANCELED", "لغو شده"),
                ],
                default="PENDING",
                max_length=20,
                verbose_name="وضعیت اشتراک",
            ),
        ),
    ]
