# Generated by Django 5.2.1 on 2025-10-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0002_alter_subscription_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="payment_amount",
            field=models.DecimalField(
                decimal_places=0,
                help_text="مبلغ واقعی که کاربر پرداخت کرده (بعد از تخفیف)",
                max_digits=12,
                verbose_name="مبلغ پرداختی (ریال)",
            ),
        ),
    ]
