# Generated by Django 5.2.1 on 2025-10-09 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0003_alter_subscription_payment_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="price",
            field=models.IntegerField(default=0, verbose_name="قیمت (ریال)"),
        ),
    ]
