# Generated by Django 6.0.6 on 2026-06-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_alter_plan_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام ویژگی')),
                ('slug', models.SlugField(unique=True, verbose_name='شناسه یکتا (Slug)')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
            ],
        ),
        migrations.AddField(
            model_name='membership',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='memberships', to='subscriptions.feature', verbose_name='ویژگی\u200cها و دسترسی\u200cها'),
        ),
    ]
