# Generated by Django 6.0.6 on 2026-06-18 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_feature_membership_features'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={'ordering': ['feature_type', 'name'], 'verbose_name': 'ویژگی', 'verbose_name_plural': 'ویژگی\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='membership',
            options={'ordering': ['title'], 'verbose_name': 'نوع اشتراک', 'verbose_name_plural': 'انواع اشتراک'},
        ),
        migrations.AddField(
            model_name='feature',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AddField(
            model_name='feature',
            name='feature_type',
            field=models.CharField(choices=[('prescription_access', 'دسترسی به نسخه\u200cهای پریمیوم'), ('ordering_access', 'دسترسی به اوردرهای پزشکی')], default='prescription_access', max_length=50, verbose_name='نوع فیچر'),
        ),
        migrations.AddField(
            model_name='feature',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AddField(
            model_name='feature',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='slug',
            field=models.SlugField(editable=False, unique=True, verbose_name='شناسه یکتا'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
    ]
