# Generated by Django 6.0.6 on 2026-07-20 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_alter_feature_options_alter_membership_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='tag',
            field=models.CharField(blank=True, choices=[('most_popular', 'محبوب\u200cترین'), ('best_value', 'به\u200cصرفه\u200cترین'), ('special_offer', 'پیشنهاد ویژه'), ('discounted', 'پیشنهاد ویژه')], max_length=50, null=True, verbose_name='برچسب نمایشی'),
        ),
    ]
