# Generated by Django 6.0.6 on 2026-08-19 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_plan_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='tag',
            field=models.CharField(blank=True, choices=[('most_popular', 'محبوب\u200cترین'), ('best_value', 'به\u200cصرفه\u200cترین'), ('special_offer', 'پیشنهاد ویژه'), ('discounted', 'تخفیف ویژه')], max_length=50, null=True, verbose_name='برچسب نمایشی'),
        ),
    ]
