# Generated by Django 5.2.1 on 2025-09-16 16:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DiscountCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=20, unique=True, verbose_name="کد تخفیف"
                    ),
                ),
                (
                    "discount_percent",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="درصد تخفیف",
                    ),
                ),
                (
                    "start_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="معتبر از تاریخ"
                    ),
                ),
                (
                    "end_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="معتبر تا تاریخ"
                    ),
                ),
                (
                    "max_usage",
                    models.PositiveIntegerField(
                        default=100, verbose_name="حداکثر تعداد استفاده"
                    ),
                ),
                (
                    "usage_count",
                    models.PositiveIntegerField(
                        default=0, editable=False, verbose_name="تعداد استفاده شده"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="فعال است؟"),
                ),
            ],
        ),
    ]
