# Generated by Django 5.2.6 on 2025-09-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="discountcode",
            name="title",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
