# Generated by Django 5.2.10 on 2026-05-19 22:30

import apps.ordering.models.order_image
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prescriptions', '0012_alter_prescriptionimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='مثال: "if SBP≥90, PR≥60"، "در صورت تهوع"', verbose_name='متن شرط')),
                ('order_index', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
            ],
            options={
                'verbose_name': 'شرط',
                'verbose_name_plural': 'شرط\u200cها',
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='DynamicFieldGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='مثال: «تشخیص افتراقی»، «تعاریف»، «ارزیابی»', max_length=200, verbose_name='عنوان گروه')),
                ('order_index', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش پیش\u200cفرض')),
                ('color', models.CharField(blank=True, choices=[('slate', 'اسلیت (خاکستری\u200cآبی)'), ('gray', 'خاکستری'), ('zinc', 'زینک'), ('neutral', 'خنثی'), ('stone', 'سنگی'), ('red', 'قرمز'), ('orange', 'نارنجی'), ('amber', 'کهربایی'), ('yellow', 'زرد'), ('lime', 'لیمویی'), ('green', 'سبز'), ('emerald', 'زمردی'), ('teal', 'فیروزه\u200cای'), ('cyan', 'آبی\u200cفیروزه\u200cای'), ('sky', 'آبی آسمانی'), ('blue', 'آبی'), ('indigo', 'نیلی'), ('violet', 'بنفش'), ('purple', 'ارغوانی'), ('fuchsia', 'فوشیا'), ('pink', 'صورتی'), ('rose', 'گلی'), ('magenta', 'سرخابی'), ('olive', 'زیتونی')], help_text='رنگ نمایشی این گروه در رابط کاربری', max_length=30, verbose_name='رنگ گروه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان بروزرسانی')),
            ],
            options={
                'verbose_name': 'گروه فیلد پویا',
                'verbose_name_plural': 'گروه\u200cهای فیلد پویا',
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyDisposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='عنوان بخش تعیین تکلیف (اختیاری)', max_length=200, verbose_name='عنوان کلی')),
                ('color', models.CharField(blank=True, choices=[('slate', 'اسلیت (خاکستری\u200cآبی)'), ('gray', 'خاکستری'), ('zinc', 'زینک'), ('neutral', 'خنثی'), ('stone', 'سنگی'), ('red', 'قرمز'), ('orange', 'نارنجی'), ('amber', 'کهربایی'), ('yellow', 'زرد'), ('lime', 'لیمویی'), ('green', 'سبز'), ('emerald', 'زمردی'), ('teal', 'فیروزه\u200cای'), ('cyan', 'آبی\u200cفیروزه\u200cای'), ('sky', 'آبی آسمانی'), ('blue', 'آبی'), ('indigo', 'نیلی'), ('violet', 'بنفش'), ('purple', 'ارغوانی'), ('fuchsia', 'فوشیا'), ('pink', 'صورتی'), ('rose', 'گلی'), ('magenta', 'سرخابی'), ('olive', 'زیتونی')], help_text='رنگ نمایشی این گره در رابط کاربری', max_length=30, verbose_name='رنگ گره')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات کلی تعیین تکلیف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان بروزرسانی')),
            ],
            options={
                'verbose_name': 'تعیین تکلیف اورژانس',
                'verbose_name_plural': 'تعیین تکلیف\u200cهای اورژانس',
            },
        ),
        migrations.CreateModel(
            name='DynamicFieldSubGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان زیرگروه')),
                ('order_index', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان بروزرسانی')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subgroups', to='ordering.dynamicfieldgroup', verbose_name='گروه مرجع')),
            ],
            options={
                'verbose_name': 'زیرگروه فیلد پویا',
                'verbose_name_plural': 'زیرگروه\u200cهای فیلد پویا',
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='DynamicFieldItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200, verbose_name='کلید (Key)')),
                ('value', models.TextField(verbose_name='مقدار (Value)')),
                ('order_index', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان بروزرسانی')),
                ('subgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ordering.dynamicfieldsubgroup', verbose_name='زیرگروه مرجع')),
            ],
            options={
                'verbose_name': 'آیتم فیلد پویا',
                'verbose_name_plural': 'آیتم\u200cهای فیلد پویا',
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='مثال: "STEMI"، "اصل کلی"، "بیماران کم\u200cخطر"', max_length=200, verbose_name='عنوان گره')),
                ('content', models.TextField(blank=True, help_text='محتوای اصلی این گره', verbose_name='متن / محتوا')),
                ('internal_notes', models.TextField(blank=True, help_text='توضیحات تکمیلی هر گره', verbose_name='توضیحات داخلی')),
                ('order_index', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('color', models.CharField(blank=True, choices=[('slate', 'اسلیت (خاکستری\u200cآبی)'), ('gray', 'خاکستری'), ('zinc', 'زینک'), ('neutral', 'خنثی'), ('stone', 'سنگی'), ('red', 'قرمز'), ('orange', 'نارنجی'), ('amber', 'کهربایی'), ('yellow', 'زرد'), ('lime', 'لیمویی'), ('green', 'سبز'), ('emerald', 'زمردی'), ('teal', 'فیروزه\u200cای'), ('cyan', 'آبی\u200cفیروزه\u200cای'), ('sky', 'آبی آسمانی'), ('blue', 'آبی'), ('indigo', 'نیلی'), ('violet', 'بنفش'), ('purple', 'ارغوانی'), ('fuchsia', 'فوشیا'), ('pink', 'صورتی'), ('rose', 'گلی'), ('magenta', 'سرخابی'), ('olive', 'زیتونی')], help_text='رنگ نمایشی این گره در رابط کاربری', max_length=30, verbose_name='رنگ گره')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان بروزرسانی')),
                ('disposition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='ordering.emergencydisposition', verbose_name='تعیین تکلیف مرجع')),
                ('parent', models.ForeignKey(blank=True, help_text='برای ایجاد ساختار درختی. خالی = گره ریشه', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='ordering.emergencynode', verbose_name='گره والد')),
            ],
            options={
                'verbose_name': 'گره تعیین تکلیف',
                'verbose_name_plural': 'گره\u200cهای تعیین تکلیف',
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='نام اوردر در حال ایجاد', max_length=150, verbose_name='نام اوردر')),
                ('imp', models.TextField(help_text='تشخیص اصلی پزشک', verbose_name='Impression / تشخیص اصلی')),
                ('condition', models.TextField(help_text='وضعیت فعلی بیمار', verbose_name='Condition / وضعیت بیمار')),
                ('diet', models.TextField(help_text='رژیم غذایی تجویزشده', verbose_name='Diet / رژیم غذایی')),
                ('action', models.TextField(help_text='اقدامات درمانی لازم', verbose_name='Action / اقدام')),
                ('position', models.TextField(help_text='وضعیت قرارگیری بیمار', verbose_name='Position / وضعیت قرارگیری')),
                ('notes', models.TextField(blank=True, help_text='توضیحات تکمیلی (مثلاً شرح وضعیت Condition)', verbose_name='توضیحات کلی Order')),
                ('color', models.CharField(blank=True, choices=[('slate', 'اسلیت (خاکستری\u200cآبی)'), ('gray', 'خاکستری'), ('zinc', 'زینک'), ('neutral', 'خنثی'), ('stone', 'سنگی'), ('red', 'قرمز'), ('orange', 'نارنجی'), ('amber', 'کهربایی'), ('yellow', 'زرد'), ('lime', 'لیمویی'), ('green', 'سبز'), ('emerald', 'زمردی'), ('teal', 'فیروزه\u200cای'), ('cyan', 'آبی\u200cفیروزه\u200cای'), ('sky', 'آبی آسمانی'), ('blue', 'آبی'), ('indigo', 'نیلی'), ('violet', 'بنفش'), ('purple', 'ارغوانی'), ('fuchsia', 'فوشیا'), ('pink', 'صورتی'), ('rose', 'گلی'), ('magenta', 'سرخابی'), ('olive', 'زیتونی')], help_text='رنگ نمایشی این Order در رابط کاربری', max_length=30, verbose_name='رنگ Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان بروزرسانی')),
                ('category', models.ForeignKey(help_text='دسته\u200cبندی اجباری است — هر Order حتماً باید دسته داشته باشد', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='prescriptions.prescriptioncategory', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='emergencydisposition',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_disposition', to='ordering.order', verbose_name='Order مرجع'),
        ),
        migrations.AddField(
            model_name='dynamicfieldgroup',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_field_groups', to='ordering.order'),
        ),
        migrations.CreateModel(
            name='OrderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.ordering.models.order_image.get_order_image_path, verbose_name='فایل تصویر')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='کپشن تصویر')),
                ('is_compressed', models.BooleanField(default=False, verbose_name='فشرده شده؟')),
                ('order_index', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان بروزرسانی')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ordering.order', verbose_name='Order مرجع')),
            ],
            options={
                'verbose_name': 'تصویر Order',
                'verbose_name_plural': 'تصاویر Order',
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='OrderSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='مثال: "Monitoring & nursing"، "Drugs"، "Imaging"', max_length=200, verbose_name='عنوان Section')),
                ('notes', models.TextField(blank=True, help_text='توضیحاتی که به کل Section مربوط است، نه به یک آیتم خاص', verbose_name='توضیحات کلی Section')),
                ('is_drug_section', models.BooleanField(default=False, help_text='در صورت فعال بودن، امکان انتخاب دارو از بانک داروهای موجود فعال می\u200cشود', verbose_name='بخش داروهاست؟')),
                ('order_index', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('color', models.CharField(blank=True, choices=[('slate', 'اسلیت (خاکستری\u200cآبی)'), ('gray', 'خاکستری'), ('zinc', 'زینک'), ('neutral', 'خنثی'), ('stone', 'سنگی'), ('red', 'قرمز'), ('orange', 'نارنجی'), ('amber', 'کهربایی'), ('yellow', 'زرد'), ('lime', 'لیمویی'), ('green', 'سبز'), ('emerald', 'زمردی'), ('teal', 'فیروزه\u200cای'), ('cyan', 'آبی\u200cفیروزه\u200cای'), ('sky', 'آبی آسمانی'), ('blue', 'آبی'), ('indigo', 'نیلی'), ('violet', 'بنفش'), ('purple', 'ارغوانی'), ('fuchsia', 'فوشیا'), ('pink', 'صورتی'), ('rose', 'گلی'), ('magenta', 'سرخابی'), ('olive', 'زیتونی')], help_text='رنگ نمایشی این Section در رابط کاربری', max_length=30, verbose_name='رنگ Section')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان بروزرسانی')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='ordering.order', verbose_name='Order مرجع')),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='DrugSectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات اضافی دارو در این Order')),
                ('order_index', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان بروزرسانی')),
                ('conditions', models.ManyToManyField(blank=True, related_name='drug_items', to='ordering.condition', verbose_name='شرط\u200cها')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_drug_items', to='prescriptions.drug', verbose_name='داروی انتخابی')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drug_items', to='ordering.ordersection', verbose_name='Section مرجع')),
            ],
            options={
                'verbose_name': 'دارو در Section',
                'verbose_name_plural': 'داروهای Section',
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='OrderVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(help_text='لینک embed از آپارات، یوتیوب و سایر پلتفرم\u200cها', verbose_name='لینک ویدیو (آپارات)')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='عنوان ویدیو')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('order_index', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان بروزرسانی')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='ordering.order', verbose_name='Order مرجع')),
            ],
            options={
                'verbose_name': 'ویدیو Order',
                'verbose_name_plural': 'ویدیوهای Order',
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='SectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن آیتم')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات اختصاصی آیتم')),
                ('order_index', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان بروزرسانی')),
                ('conditions', models.ManyToManyField(blank=True, related_name='section_items', to='ordering.condition', verbose_name='شرط\u200cها')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ordering.ordersection', verbose_name='Section مرجع')),
            ],
            options={
                'verbose_name': 'آیتم Section',
                'verbose_name_plural': 'آیتم\u200cهای Section',
                'ordering': ['order_index'],
            },
        ),
    ]
