# Generated by Django 5.2.10 on 2026-05-24 00:21

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergencynode',
            name='internal_notes',
        ),
        migrations.AlterField(
            model_name='emergencynode',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='محتوای اصلی این گره — با فرمت\u200cبندی غنی', verbose_name='محتوا'),
        ),
    ]
