# Generated by Django 5.2.10 on 2026-06-08 19:47

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0002_remove_emergencynode_internal_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dynamicfieldsubgroup',
            name='group',
        ),
        migrations.AddField(
            model_name='dynamicfieldgroup',
            name='notes',
            field=models.TextField(blank=True, verbose_name='توضیحات کلی'),
        ),
        migrations.AlterField(
            model_name='dynamicfieldgroup',
            name='color',
            field=models.CharField(blank=True, choices=[('slate', 'اسلیت (خاکستری\u200cآبی)'), ('gray', 'خاکستری'), ('zinc', 'زینک'), ('neutral', 'خنثی'), ('stone', 'سنگی'), ('red', 'قرمز'), ('orange', 'نارنجی'), ('amber', 'کهربایی'), ('yellow', 'زرد'), ('lime', 'لیمویی'), ('green', 'سبز'), ('emerald', 'زمردی'), ('teal', 'فیروزه\u200cای'), ('cyan', 'آبی\u200cفیروزه\u200cای'), ('sky', 'آبی آسمانی'), ('blue', 'آبی'), ('indigo', 'نیلی'), ('violet', 'بنفش'), ('purple', 'ارغوانی'), ('fuchsia', 'فوشیا'), ('pink', 'صورتی'), ('rose', 'گلی'), ('magenta', 'سرخابی'), ('olive', 'زیتونی')], max_length=30, verbose_name='رنگ گروه'),
        ),
        migrations.AlterField(
            model_name='dynamicfieldgroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='dynamicfieldgroup',
            name='order_index',
            field=models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش'),
        ),
        migrations.AlterField(
            model_name='dynamicfieldgroup',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان گروه'),
        ),
        migrations.AlterField(
            model_name='dynamicfieldgroup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='DynamicFieldNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان گره')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='محتوا')),
                ('order_index', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('color', models.CharField(blank=True, choices=[('slate', 'اسلیت (خاکستری\u200cآبی)'), ('gray', 'خاکستری'), ('zinc', 'زینک'), ('neutral', 'خنثی'), ('stone', 'سنگی'), ('red', 'قرمز'), ('orange', 'نارنجی'), ('amber', 'کهربایی'), ('yellow', 'زرد'), ('lime', 'لیمویی'), ('green', 'سبز'), ('emerald', 'زمردی'), ('teal', 'فیروزه\u200cای'), ('cyan', 'آبی\u200cفیروزه\u200cای'), ('sky', 'آبی آسمانی'), ('blue', 'آبی'), ('indigo', 'نیلی'), ('violet', 'بنفش'), ('purple', 'ارغوانی'), ('fuchsia', 'فوشیا'), ('pink', 'صورتی'), ('rose', 'گلی'), ('magenta', 'سرخابی'), ('olive', 'زیتونی')], max_length=30, verbose_name='رنگ گره')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='ordering.dynamicfieldgroup', verbose_name='گروه مرجع')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='ordering.dynamicfieldnode', verbose_name='گره والد')),
            ],
            options={
                'verbose_name': 'گره فیلد پویا',
                'verbose_name_plural': 'گره\u200cهای فیلد پویا',
                'ordering': ['order_index'],
            },
        ),
        migrations.DeleteModel(
            name='DynamicFieldItem',
        ),
        migrations.DeleteModel(
            name='DynamicFieldSubGroup',
        ),
    ]
