# Generated by Django 6.0.6 on 2026-06-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0003_remove_dynamicfieldsubgroup_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='action_notes',
            field=models.TextField(blank=True, help_text='توضیحات تکمیلی مربوط به اقدامات درمانی', null=True, verbose_name='توضیحات Action'),
        ),
        migrations.AddField(
            model_name='order',
            name='condition_notes',
            field=models.TextField(blank=True, help_text='توضیحات تکمیلی مربوط به وضعیت بیمار', null=True, verbose_name='توضیحات Condition'),
        ),
        migrations.AddField(
            model_name='order',
            name='diet_notes',
            field=models.TextField(blank=True, help_text='توضیحات تکمیلی مربوط به رژیم غذایی', null=True, verbose_name='توضیحات Diet'),
        ),
        migrations.AddField(
            model_name='order',
            name='imp_notes',
            field=models.TextField(blank=True, help_text='توضیحات تکمیلی مربوط به تشخیص اصلی', null=True, verbose_name='توضیحات Impression'),
        ),
        migrations.AddField(
            model_name='order',
            name='position_notes',
            field=models.TextField(blank=True, help_text='توضیحات تکمیلی مربوط به وضعیت قرارگیری بیمار', null=True, verbose_name='توضیحات Position'),
        ),
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, help_text='توضیحات تکمیلی کلی درباره این Order', null=True, verbose_name='توضیحات کلی Order'),
        ),
    ]
