# Generated by Django 6.0.6 on 2026-06-18 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0004_order_action_notes_order_condition_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='slug',
            field=models.SlugField(blank=True, help_text='شناسه یکتای URL-friendly برای Order', max_length=200, null=True, unique=True, verbose_name='اسلاگ'),
        ),
    ]
