# Generated by Django 6.0.6 on 2026-06-23 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0006_order_access_level_alter_dynamicfieldgroup_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemRelationshipGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(choices=[('OR', 'یا (OR)'), ('AND', 'و (AND)')], default='OR', max_length=3, verbose_name='اپراتور منطقی')),
                ('order_index', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش گروه')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationship_groups', to='ordering.ordersection', verbose_name='سکشن مرجع')),
            ],
            options={
                'verbose_name': 'گروه ارتباطی آیتم\u200cها',
                'verbose_name_plural': 'گروه\u200cهای ارتباطی آیتم\u200cها',
                'ordering': ['order_index'],
            },
        ),
        migrations.AddField(
            model_name='drugsectionitem',
            name='relationship_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drug_items', to='ordering.itemrelationshipgroup', verbose_name='گروه ارتباطی'),
        ),
        migrations.AddField(
            model_name='sectionitem',
            name='relationship_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='text_items', to='ordering.itemrelationshipgroup', verbose_name='گروه ارتباطی'),
        ),
    ]
