# Generated by Django 6.0.6 on 2026-06-26 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0007_itemrelationshipgroup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemrelationshipgroup',
            name='operator',
            field=models.CharField(choices=[('OR', 'یا (OR)'), ('AND', 'و (AND)'), ('THEN', 'و (THEN)')], default='OR', max_length=10, verbose_name='اپراتور منطقی'),
        ),
    ]
