# Generated by Django 6.0.6 on 2026-06-28 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0008_alter_itemrelationshipgroup_operator'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام جایگزین')),
                ('is_primary', models.BooleanField(default=False, help_text='آیا این نام اصلی Order است؟', verbose_name='نام اصلی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='ordering.order', verbose_name='اوردر')),
            ],
            options={
                'verbose_name': 'نام جایگزین',
                'verbose_name_plural': 'نام\u200cهای جایگزین',
                'unique_together': {('order', 'name')},
            },
        ),
    ]
