# Generated by Django 6.0.6 on 2026-07-04 10:20

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0009_orderalias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugsectionitem',
            name='notes',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='توضیحات اضافی دارو در این Order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='action',
            field=models.TextField(help_text='اقدامات درمانی لازم', verbose_name='Activity / فعالیت'),
        ),
        migrations.AlterField(
            model_name='sectionitem',
            name='notes',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='توضیحات اختصاصی آیتم'),
        ),
    ]
