# Generated by Django 6.0.6 on 2026-07-08 14:37

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0010_alter_drugsectionitem_notes_alter_order_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersection',
            name='notes',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='توضیحاتی که به کل Section مربوط است، نه به یک آیتم خاص', verbose_name='توضیحات کلی Section'),
        ),
    ]
