# Generated by Django 6.0.6 on 2026-08-19 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0011_alter_ordersection_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_active',
            field=models.BooleanField(default=True, help_text='در صورت غیرفعال بودن، این اوردر در لیست\u200cهای عمومی نمایش داده نمی\u200cشود', verbose_name='فعال'),
        ),
    ]
