# Generated by Django 5.2.6 on 2025-09-17 09:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("subscriptions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="شناسه تراکنش",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "در انتظار پرداخت"),
                            ("COMPLETED", "تکمیل شده"),
                            ("FAILED", "ناموفق"),
                            ("CANCELLED", "لغو شده"),
                        ],
                        default="PENDING",
                        max_length=12,
                        verbose_name="وضعیت پرداخت",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0, max_digits=10, verbose_name="مبلغ (ریال)"
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="مبلغ تخفیف (ریال)",
                    ),
                ),
                (
                    "final_amount",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=12,
                        verbose_name="مبلغ نهایی (ریال)",
                    ),
                ),
                (
                    "authority",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="کد رهگیری درگاه"
                    ),
                ),
                (
                    "ref_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="شماره مرجع تراکنش",
                    ),
                ),
                (
                    "user_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="آی\u200cپی کاربر"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True, null=True, verbose_name="اطلاعات مرورگر"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاریخ ایجاد تراکنش"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاریخ پرداخت"
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="subscriptions.subscription",
                        verbose_name="اشتراک مربوطه",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="payment_pay_user_id_94fc9f_idx"
                    ),
                    models.Index(
                        fields=["authority"], name="payment_pay_authori_8e0a58_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="payment_pay_created_671024_idx"
                    ),
                ],
            },
        ),
    ]
