# Generated by Django 5.2.1 on 2025-10-09 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="gateway",
            field=models.CharField(
                choices=[("ZARINPAL", "زرین\u200cپال"), ("PARSPAL", "پارس\u200cپال")],
                default="ZARINPAL",
                max_length=20,
                verbose_name="درگاه پرداخت",
            ),
        ),
    ]
