# Generated by Django 5.2.1 on 2025-10-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0002_payment_gateway"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="authority",
            field=models.CharField(max_length=255, verbose_name="کد رهگیری درگاه"),
        ),
    ]
