# Generated by Django 5.2.7 on 2025-11-22 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="title",
            field=models.CharField(
                default="اعلان جدید", max_length=100, verbose_name="عنوان اعلان"
            ),
        ),
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="عنوان")),
                ("message", models.TextField(verbose_name="متن پیام")),
                (
                    "target_role",
                    models.CharField(
                        choices=[
                            ("all", "همه کاربران"),
                            ("visitor", "بازدیدکنندگان"),
                            ("regular", "کاربران عادی"),
                            ("premium", "کاربران ویژه"),
                        ],
                        max_length=20,
                        verbose_name="نقش هدف",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_sent",
                    models.BooleanField(default=False, verbose_name="ارسال شده؟"),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ارسال کننده",
                    ),
                ),
            ],
        ),
    ]
