# Generated by Django 5.2.7 on 2025-11-23 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_notification_title_announcement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="message",
            field=models.TextField(verbose_name="متن اعلان"),
        ),
    ]
